# Generated by Django 3.2.3 on 2021-05-23 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsale',
            name='sales',
            field=models.ManyToManyField(to='dashboard.Sale'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='purchases',
            field=models.ManyToManyField(to='dashboard.Purchase'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='product_purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productpurchase'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='product_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productsale'),
        ),
    ]
